### ISSUE TITLE
각 타입의 리터럴

### ISSUE THREAD

**Issue by ENvironmentSet** [Tteoksal/proposals#10]
각 타입의 리터럴을 아래와 같이 제안합니다.

타입 | 리터럴
----- | ----- |
number | 16진수의 경우 : 0x prefix를 붙인다. 2진수의 경우 : 0b prefix를 붙이며, 그 외 경우는 아라비아 숫자 표기법을 따른다.
string | "로 둘러쌓인 utf-8 문자들의 열
boolean | true와 false로 참/거짓을 나타낸다
function | (매개변수 타입, ...): 반환값의 타입 형태로 나타낸다.
container | #6 참고
array | [요소, ...]
객체 | { 속성명: 속성값 }

**Comment by seeeturtle** [comment]
@ENvironmentSet 
array는 리스트를 이용해서 `<li>e1 e2 e3...<li/>`로 하면 어떨까요?

**Comment by ENvironmentSet** [comment]
@seeeturtle

그건 리터럴이라기보다는 li 함수를 호출함으로서 array를 만든다고 보는게 맞는 거 같네요.

**Comment by seeeturtle** [comment]
@ENvironmentSet 
리터럴이라고 보는 게 맞다고 생각합니다.
왜냐하면 언어 상에서 array를 만드는 방법이 저거 밖에 없거든요...

사실 literal은 자신 마음일 것 같습니다.
let같은 것도 사용자가 직접 구현할 수 는 없잖아요

**Comment by ENvironmentSet** [comment]
그렇기에 []를 통한 방식을 리터럴로 만드는 게 어떨까요?

**Comment by seeeturtle** [comment]
약간 문제가 있는 게 언어 특성상 list 가 많이 쓰이는데 그럼 모든 곳 이 다 []로 될 가능성도 있어서...

예로들어:
```
<define>
<li>foo 
bar
... // argument
<li/>
... // body
<define/>
 ```
를
```
[define [foo bar ...] ...]
```
로 바꿔버리는...

**Comment by ENvironmentSet** [comment]
하지만 컨테이너나 함수, 객체를.제외한 값들을 표현할 때에는 매우 효율적인 방법이라고 생각됩니다.

또한 위에서 보여주신 케이스 관련은 아직 논의되지 않았으므로 부적절한 예시라고 생각합니다.

**Comment by seeeturtle** [comment]
number, string, boolean와 같이 단순한 것들을 제외하고는
container를 이용한 방식을 선택하는 것이 좋지 않을 까 싶네요.

**Comment by ENvironmentSet** [comment]
컨테이너를 이용한 방식, 리터럴을 이용한 방식. 두 개의 선택권을 주는 것이지요. 
각각의 장단점이 있으니 저는 추가해도 문제가 없다고 생각합니다.

**Comment by seeeturtle** [comment]
선택권을 다양하게 하는 것은 좋습니다.
하지만 언어자체를 완전히 lisp처럼 바꿀 수 있는 선택입니다.
완전히 떡 언어의 identity를 없애버릴 수 있는 선택권은...
안 하는게 좋다고 생각합니다

**Comment by ENvironmentSet** [comment]
컨테이너와 관련된 문법이 팀원마다 조금씩 다른 거 같네요. 이 부분은 새로 이슈을 만들어서 이야기를 나누어야 할 거 같습니다. 먼저 컨테이너 관련한 내용을 정리하고 이후에 이 이슈를 다루는 게 어떨까요?

**Comment by seeeturtle** [comment]
> [define [foo bar ...] ...]

여기서 제가 함수 콜을 `<li>function ...</li>`로 가정했는데 
생각해보니 이런 evaluate가 가능한 것들과 그냥 리스트를 구분해야하기 위해 array 리터럴이 필요한 것 같아요.

예로 들어 리스트를 인자로 받는 함수 foo가 있을때,
`<li>foo <li>1 2 3</li></li>`에서 1이 두개의 인자를 받는 함수인지, 
리스트의 요소 중 하나인지는 알 수가 없죠.
@ENvironmentSet

**Comment by seeeturtle** [comment]
https://gist.github.com/ENvironmentSet/41dfeb26bd78491a3a3aee39a34f82cb
에 정리되어있습니다.
gist에 답글을 달거나 여기에 의견을 정리해서 적어주세요

**Comment by ENvironmentSet** [comment]
@seeturtle
실수 표기법이 누락되었는데. 추가 가능하시나요?

**Comment by ENvironmentSet** [comment]
더 이상 유효하지 않은 이슈 - 프로젝트의 대대적 수정
