### ISSUE TITLE
해시테이블과 객체의 합병

### ISSUE THREAD

**Issue by ENvironmentSet** [Tteoksal/proposals#11]
해시 테이블과 객체의 합병을 제안합니다.

* 객체의 프로퍼티를 동적으로 추가/삭제 가능하다는 점 에서 해시테이블의 역할을 할 수 있음.
* 내부적으로 속성명 : 값 매칭을 해시테이블을 이용한다면 객체의 성능 향상 가능.

**Comment by seeeturtle** [comment]
@ENvironmentSet 
만약 객체가 동적으로 property를 추가/삭제할 수 있다면 해시테이블과 기능적으로 거의 차이가 없으므로 합쳐도 문제가 없다고 생각합니다 .

근데 객체를 동적으로 property를 추가/삭제를 할 수 있게 하는 게 맞는 지는 모르겠네요.
이 부분은 논의가 필요한 듯 합니다.

**Comment by jwmsg0525** [comment]
음 사실 추가나 삭제 기능있는 객체가 있으면 고정적 객체는 필요가 없어지죠...(사실 나중되면 다들 맵 쓰는것처럼) 추가 제거 기능을 넣고 합쳐도 무방하다 봅니다.

**Comment by seeeturtle** [comment]
@maxswjeon 
물론 동적인 객체가 생기면 불변 객체는 필요가 없어지죠.
그런데 여기서 문제는 불변 객체를 지향하는 것이 옳은가 가변 객체를 지향하는 것이 옳은가에 대해서 논의가 필요한다는 것입니다.

**Comment by jwmsg0525** [comment]
흠... 불변객체가 가끔씩 편리함을 제공해 주긴 하는데.... 가변객체가 있으면 딱히 불변객체에 대하 필요성이 줄어들다보니 굳이 따로 불변객체가 있어야 하는가... 생각이 듭니다. 저는 동적인 객체로 합병하는거에 찬성하는 입장입니다.

**Comment by seeeturtle** [comment]
저는 이미 hash table이 있으므로 그냥 object를 불변 객체로 남기는 것이 맞다고 생각합니다.
그러니까 동적인 객체로 합병하는 데에는 반대합니다.

**Comment by jwmsg0525** [comment]
사용률이 저조할듯 하네요.
그리고 동적 해시테이블이 이미 일반 불변 객체의 기능을 대신 할 수 있기에.. 필요성을 못느끼겠어요.

**Comment by seeeturtle** [comment]
흠... 그렇다 하더라도 불변 객체와 가변 객체는 서로 확실한 단장점을 가지고 있으므로 있는게 좋다고 생각합니다

**Comment by ENvironmentSet** [comment]
동적인 객체를 Lock 할 수 있게 하는 건 어떨까요? 자바스크립트에는 객체를 불변으로 만드는 여러 메서드들이 있습니다(Object.freeze, Object.seal, Object.preventExtensions) 이런 메서드들을 도입하는 건 어떨까요?

**Comment by seeeturtle** [comment]
아예 없애거나 분리 시키는 것이 맞다고 생각합니다.
옵션으로 가변 객체와 불변 객체를 구분하는 건 아니라고 생각합니다.

2018. 5. 10. 오전 1:07 서재원 <notifications@github.com> 작성:

**Comment by ENvironmentSet** [comment]
하지만 언어를 더욱 직교적으로 만들 수 있다고 생각합니다.

이런 말이 있습니다

"10개의 데이터 구조에 10개의 함수가 있는 것 보다, 1개의 데이터 구조에 100개의 함수가 있는 것이 더 좋다" - 앨런 펄리스

**Comment by seeeturtle** [comment]
제가 생각한 객체는 필드의 추가/삭제가 불가능하고
메서드를 정의할 수 있고,

해시테이블은 메서드는 정의할 수 없지만,
필드의 추가/삭제가 가능한 타입입니다.

그러니까 좀 다르다고 할 수 있죠

2018. 5. 11. 오전 8:37 서재원 <notifications@github.com> 작성:

**Comment by ENvironmentSet** [comment]
메서드도 결국 해시테이블에 함수를 담음으로써 표현할 수 있지 않을까요?

객체에서 가능한 게 해시테이블에서도 가능하니 그냥 합치는 게 맞다고 봅니다.

**Comment by seeeturtle** [comment]
흠...
객체를 OOP의 요소로써 재사용이 가능하도록 만든다면 있는 것도 나쁘지 않다고 생각합니다

**Comment by ENvironmentSet** [comment]
prototype base OOP는 어떠신가요?

**Comment by seeeturtle** [comment]
네 그렇게 가는게 좋을 것 같네요
최소한 클래스 기반 OOP는 안 갔으면 좋을 것 같아요

**Comment by ENvironmentSet** [comment]
결정된 이슈 -  외부 회의 결과
객체의 확장을 통한 상속 + 해시 테이블과 객체의 합병
