### ISSUE TITLE
컨테이너의 기본 형태

### ISSUE THREAD

**Issue by ENvironmentSet** [Tteoksal/proposals#13]
### 소개
컨테이너의 기본 형태를 정의하는 제안입니다.

### 필요성
떡의 전부인 컨테이너에 대한 세부 정의입니다.

### 세부 내용
[container 의 EBNF](https://gist.github.com/ENvironmentSet/2d22984c251d21b121e936b0c840d701)

사용예제 : 

    <def>
      x 1
    </def>

**Comment by seeeturtle** [comment]
test message

**Comment by ENvironmentSet** [comment]
더 이상 유효하지 않은 이슈 - 프로젝트의 대대적 수정
