### ISSUE TITLE
컨테이너의 정의

### ISSUE THREAD

**Issue by seeeturtle** [Tteoksal/proposals#14]
### 소개
컨테이너의 정의 방법입니다

### 필요성
현재 존재하지 않는 컨테이너를 정의하는 방법을 만듭니다

### 세부 내용
```html
<mycont arg1="foo" arg2=123>body1 body2</mycont>
```
위와 같은 컨테이너를
아래와 같이 나타낼 수 있습니다
```html
<container arg="foo" arg2=123>mycont body1 body2</container>
```
* 문법 제안의 경우 [EBNF](https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_form)는 필수입니다.
* 기존 스펙을 수정하는 경우 수정되는 부분을 명시해주세요.
* 제안이 두드러지게 나타는 예를 나타내주세요.

**Comment by ENvironmentSet** [comment]
더 이상 유효하지 않은 이슈 - 프로젝트의 대대적 수정
