### ISSUE TITLE
떡의 컨셉

### ISSUE THREAD

**Issue by ENvironmentSet** [Tteoksal/proposals#2]
떡의 컨셉으로 '시각적이며 간단하고, 명료한 프로그래밍 언어' 를 하려 하는데 여러분의 생각은 어떠신가요?
프로그래밍 패러다임으로는 멀티-패러다임을 채택할 생각입니다.
코드의 형식은 S-Expression 이 시각적인 부분에서 강력하게 작용할 수 있기에 lisp-like 하게 만들려고 합니다.

**Comment by seeeturtle** [comment]
@seeeturtle 의 comment:
시각적인 것과 S-Expression은 잘 매치가 안되서
lisp-like, html-like, xml-like 등을 추천했습니다.

**Comment by ENvironmentSet** [comment]
lisp-like은 하나의 객관적인 형태가 정의된 게 아니기 때문에 S-Expression이라는 단어를 사용하였습니다

**Comment by ENvironmentSet** [comment]
추가적인 코맨트가 없다면 이따 이슈를 내리도록 하겠습니다.
