### ISSUE TITLE
떡의 기본 타입 추가

### ISSUE THREAD

**Issue by ENvironmentSet** [Tteoksal/proposals#4]
기본 타입(Atomic)으로 아래의 타입들을 제안하는 바 입니다.
* Number 
IEEF 754를 따르는 숫자 타입 (8 byte)
* Char
문자를 나타내는 타입 (4 byte)
* Boolean
true / false 를 나타내는 타입 (1 byte)

**Comment by seeeturtle** [comment]
괜찮은 것 같습니다.

**Comment by ENvironmentSet** [comment]
그럼 이 부분도 통과시키겠습니디
