### ISSUE TITLE
타입의 분류

### ISSUE THREAD

**Issue by ENvironmentSet** [Tteoksal/proposals#5]
타입들을 분류할 생각입니다.
아래의 조건을 충족하는 타입들은 모두 Atomic 타입이라 부르고, 그 외는 Ion 타입이라 부르는 것이 어떠신가요?

* 변수나 데이터 구조안에 담을 수 있다.
* 파라미터로 전달 할 수 있다.
* 반환값(return value)으로 사용할 수 있다.
* 값의 비트열에 메모리의 주소가 포함되지 않는다.
* 더 이상 자명한 세부 타입으로 쪼갤 수 없는 상태여야 한다. (즉, Boolean Array는 N개의 Boolean으로 쪼갤 수 있으므로  Atomic 타입이 아니지만,  Number의 경우 쪼개보았자 바이트, 비트의 열일 뿐이지 더 이상의 의미를 가지지 못하므로 Atomic 타입입니다)

**Comment by seeeturtle** [comment]
어... 내부 값이 변할 수 없는 타입을 Atomic 타입이라 하고 내부 값이 변할 수 있는 타입을 Ion 타입이라 하면 안될까요? 너무 정의가 넓게 될까요?

**Comment by jwmsg0525** [comment]
원소타입 정의 내리는듯 한데
쪼개짐의 정의로 내리지 말고
일단 만들고자 하는 타입들을 쭉 나열해보고
간단하게 문서로나마 분류만 시키면 될듯 합니다.
일단 만들어지는 타입들이 무엇들인지 부터 생각해봐야 겠네요

**Comment by seeeturtle** [comment]
#4 에서 말한 것들: 
* number
* character
* boolean

이 아마 Atomic type이 될 것 같습니다

**Comment by ENvironmentSet** [comment]
@seeeturtle  네, 그 친구들이 Atomic type 이 될 수 있겠지요

**Comment by ENvironmentSet** [comment]
@jwmsg0525 쪼개짐의 정의로 구별하면 안되는 이유가 있나요?

**Comment by seeeturtle** [comment]
우선 type들을 열거하고 분류하는 기준을 세우자는 의견인 것 같습니다

**Comment by jwmsg0525** [comment]
쪼개짐에 대하여 정의 내리는거도 좋은 의견일 수 있으나
데이터에 대한 의미에 대한 정의와
최대로 쪼개짐의 단위에 대한 정의에 대하여
 모호성이 존재할 수 있다고 봅니다.

**Comment by seeeturtle** [comment]
어쨌든 Atomic Type이라고 할 만한 것들을 모아놓고 그들의 공통점에서 시작하는 것도 나쁘지 않다고 생각합니다.

**Comment by jwmsg0525** [comment]
동의합니다

**Comment by ENvironmentSet** [comment]
이 이슈는 #7 에서 이어서 다루도록 하겠습니다
