### ISSUE TITLE
컨테이너 용어들

### ISSUE THREAD

**Issue by seeeturtle** [Tteoksal/proposals#6]
`<container1 identifier=value> body <container1/>`

위치 | 이름 | 영문
----- | ----- | ------
container1 | 태그 이름 | tag name
identfier | 태그 속성명 | tag attribute name
value | 태그 속성값 | tag attribute value
<container1 ...> | 시작 태그 | start tag
body | 몸체 | body
\<container1 /> | 종료 태그 | end tag

`<container .../>` : self-end container

**Comment by ENvironmentSet** [comment]
<container /> self-end container 라고 하는 건 어떨까요? (종료 태그와 시작 태그가 함께하는)

**Comment by ENvironmentSet** [comment]
내일까지 추가 사항이 없으면 이대로 스펙에 넣겠습니다.
