### ISSUE TITLE
Tteok 언어의 타입들

### ISSUE THREAD

**Issue by seeeturtle** [Tteoksal/proposals#7]
Atomic Type: 내부 값이 변할 수 없는 타입
* number: 숫자(IEEE 754)
* string: 불변 문자열
* boolean: true/false
* function: 함수
* container: 컨테이너

Ion Type: 내부 값이 변할 수 있는 타입
* Array: Go에서의 slice
* Hashtable: python에서의 dict, Go에서의 map
* Object: 객체(또는 structure)

**Comment by ENvironmentSet** [comment]
Cool :O 저는 이대로 스펙에 넣어도 무방하다고 생각합니다.

**Comment by jwmsg0525** [comment]
동의합니다.
그런데 추후 lon 타입에서 여러 타입들을 추가 할 수 있겠죠?

**Comment by ENvironmentSet** [comment]
네 필요하다면 추가해야지요  ㅎㅎ

**Comment by jwmsg0525** [comment]
그런데 number 타입에서 특별히 정수와 실수를 구분하지 않고 IEEE 754 에 맞춰서 실수형으로 통일해버리눈건가요?

**Comment by seeeturtle** [comment]
네 그런 것 같아요.

2018. 5. 5. 오전 1:28 JaewanJeong <notifications@github.com> 작성:

**Comment by ENvironmentSet** [comment]
네 실수형으로 통일할 생각입니다.
기회가 된다면 Bigint와 double로 나누고 싶긴 하지만 딱히 필요성을 느끼지 못하기에..

**Comment by jwmsg0525** [comment]
사실 개인적으로 저도 실수형으로 통일하는게 좋다고 생각합니다. 근데 부동소숫점 오류는 보정 할 수 있겠죠...?

**Comment by ENvironmentSet** [comment]
*지극히 정상적인* 오류이니 남길 생각입니다.

**Comment by ENvironmentSet** [comment]
더 이상의 추가 의견이 없다면 이만 클로즈하겠습니다
