### ISSUE TITLE
연산자 정의

### ISSUE THREAD

**Issue by ENvironmentSet** [Tteoksal/proposals#8]
컨테이너명 | 이름 | 사용법
----- | ----- | ------
\+ | 덧셈 연산자 | <+ <number 10/> <number 20/> /> **이 문법은 #9 를 참조해 주세요**
\-  | 뺌셈 연산자 | <- <number 30/> <number 20/> />
\*  | 곱셈 연산자 | <* <number 10/> <number 10/> />
\\  | 나눗셈 연산자 | <\\ <number 10/> <number 2/> />
% | 나머지 연산자 | <% <number 10/> <number 9/> />
\*\* | 제곱 연산자 | <** <number 10/> <number 2/> />
log' | 로그 연산자 | **추가 바람**
? | 삼항 연산자 | <? <boolean true/> <:: <number 1/> <number 2/> /> />
\|\| | 논리 or 연산자 | <\|\| \<boolean false/> \<boolean true/> />
&& :| 논리 and 연산자 | <&& \<boolean true/> \<boolean true/> />
^-, -^ | 대소관계 연산자 | <-^ <number 10/> <number 20/> />
! | 논리 not 연산자 | <! <number 10/> />
~ | 비트 not 연산자 | <~ <number 10/> />
\| | 비트 or 연산자 | <\| <number 0b01/> <number 0b10/> />
& | 비트 and 연산자 | <& <number 0b11/> <number 0b01/> />
*-, -* | 비트 shift 연산자 | <*- <number 0b001/> />
^ | 비트 xor 연산자 | <^ <number 10/> <number 20/> />

**Comment by seeeturtle** [comment]
@ENvironmentSet 
기호를 쓰는 대신에 and, or, 같이 할 수 도 있을 것 같요

**Comment by ENvironmentSet** [comment]
\<and\> 0b01 0b10 \</and\> 처럼요?

**Comment by seeeturtle** [comment]
그렇죠. 그게 더 직관적일 것 같아요.

참고로 여기서 `and`(논리 연산자)는 모든 인자가 true일때 true를 반환하고, 아니면 false를 반환하는 일종의 함수입니다

**Comment by ENvironmentSet** [comment]
알겠습니다. 오후쯤에 테이블을 수정하겠습니다

**Comment by ENvironmentSet** [comment]
더 이상 유효하지 않은 이슈 - 프로젝트의 대대적 수정
